language: java

matrix:
  include:
  - jdk: openjdk8
  - jdk: openjdk10
  - jdk: openjdk11

install: mvn install clirr:check

after_success:
  - mvn -DrepoToken=${coveralls_token} clean test jacoco:report coveralls:report --projects=saphir-hash-core

cache:
    directories:
    - $HOME/.m2
