language: java
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
  - oraclejdk9
install: mvn install -Dgpg.skip
after_success:
  - mvn -DrepoToken=${coveralls_token} clean test jacoco:report coveralls:report --projects=sudoku
