version: 2
shared: &shared
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx1g
    TERM: dumb
  steps:
    - checkout
    - restore_cache:
        key: maven-{{ checksum "pom.xml" }}
    - run:
        name: Maven Get Dependencies
        command: mvn dependency:go-offline --fail-never
    - save_cache:
        paths:
          - ~/.m2
        key: maven-{{ checksum "pom.xml" }}
    - run:
        name: Maven Build and test
        command: mvn clean package
    - run:
        name: Maven Install / Clirr check
        command: mvn install clirr:check
    - run:
        name: Maven Install / Clirr check
        command: mvn install clirr:check
    - run:
        name: Maven Upload Coverage Report
        command: mvn -DrepoToken=${coveralls_token} clean test jacoco:report coveralls:report --projects=saphir-hash-core
jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk-buster
    <<: *shared
  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk-buster
    <<: *shared
  jdk13:
    docker:
      - image: circleci/openjdk:13-jdk-buster
    <<: *shared
  jdk14:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    <<: *shared
  jdk15:
    docker:
      - image: circleci/openjdk:15-jdk-buster
    <<: *shared

workflows:
  version: 2
  work:
    jobs:
      - jdk8
      - jdk11
      - jdk13
      - jdk14
      - jdk15
